baseurl = "https://tk3.dev/"
title = "tk3.dev"
author = "tk3"
copyright = "© 2019. tk3"
languageCode = "ja-jp"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

# canonifyurls = true
paginate = 10
theme = "hugo-clarity"

# Links format
[permalinks]
  # :year, :month, :day, :title, :slug
  posts = "/posts/:year/:month/:slug/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    # style = "monokai"
    tabWidth = 2

[params]
author = "tk3"
twitter = "@tk3inc"
largeTwitterCard = false
introDescription = ""

ga_analytics = "UA-146469501-1"

numberOfTagsShown = 14

#fallBackOgImage = "img/qtkmz4.png"
fallBackOgImage = ""

codeMaxLines = 16
codeLineNumbers = false

mainSections = ["posts"]

centerLogo = false

#logo = "logos/logo.png"
logo = ""

figurePositionShow = false
figurePositionLabel = "Figure"

mobileNavigation = "left"

